# hyper parameter
epochs: 1000
batch_size: 16
lr: 1.E-4
lmd1: 1
lmd2: 2
range_norm: true
dim: 2
resnet: resnet34
thredhold: 0.9

# dataset
dataset: hela
image_path: /data/cwj/HeLa/img
label_path: null

# morphological
smooth_iter: 3

# set prepare work
summary_dir: runs
saver_dir: storages
disp_images: 5
shuffle: true
num_workers: 3
visual_freq: 100
devices: 
  # - 0
  # - 1
  # - 2
  # - 3
  - 4
  - 5
  - 6
  - 7

runtime_id: null # recommand to keep runtime_id to be null
force: false

# images settings
image_x: 512
image_y: 512
image_z: 1      # if image is 2D, set image_z to 1
suffix: tif

# resume
resume: false
resume_latest: false
resume_best: false
resume_epoch: null      # a number from 0 to max_epoch
